-- MySQL Script generated by MySQL Workbench
-- lun. 02 août 2021 16:53:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Veterinaire
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Veterinaire` ;

-- -----------------------------------------------------
-- Schema Veterinaire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Veterinaire` ;
USE `Veterinaire` ;

-- -----------------------------------------------------
-- Table `Veterinaire`.`Proprietaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Proprietaire` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Proprietaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `codePostal` INT NULL,
  `ville` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `telephoneMobile` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Animal` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Animal` (
  `Id` INT NOT NULL,
  `Nom` VARCHAR(20) NULL,
  `DateNaissance` DATE NULL,
  `DateDeces` DATE NULL,
  `idProprietaire` INT NOT NULL,
  PRIMARY KEY (`Id`, `idProprietaire`),
  CONSTRAINT `fk_Animal_1`
    FOREIGN KEY (`Id`)
    REFERENCES `Veterinaire`.`Proprietaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Race_chien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Race_chien` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Race_chien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Chien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Chien` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Chien` (
  `idAnimal` INT NOT NULL,
  `taille` VARCHAR(45) NULL,
  `Poids` VARCHAR(45) NULL,
  `idRace` INT NULL,
  INDEX `inddexAnimal` (`idAnimal` ASC) VISIBLE,
  INDEX `indexRace` (`idRace` ASC) VISIBLE,
  CONSTRAINT `fk_Animal`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Veterinaire`.`Animal` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_raceChien`
    FOREIGN KEY (`idRace`)
    REFERENCES `Veterinaire`.`Race_chien` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Race_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Race_chat` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Race_chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  INDEX `index1` USING BTREE (`id`) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Chat` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Chat` (
  `idAnimal` INT NOT NULL,
  `idRace` INT NULL,
  INDEX `indexAnimal` USING BTREE (`idAnimal`) VISIBLE,
  INDEX `indexRace` (`idRace` ASC) VISIBLE,
  CONSTRAINT `fk_Chat`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Veterinaire`.`Animal` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_raceChat`
    FOREIGN KEY (`idRace`)
    REFERENCES `Veterinaire`.`Race_chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Veterinaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Veterinaire` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Veterinaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `telephoneMobile` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Dossier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Dossier` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Dossier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `antecedents` TEXT(50) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dossier_proprietaire`
    FOREIGN KEY (`id`)
    REFERENCES `Veterinaire`.`Proprietaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Visite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Visite` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Visite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `heureVisite` TIME NULL,
  `raison` VARCHAR(45) NULL,
  `idDossier` INT NOT NULL,
  `idAnimal` INT NOT NULL,
  `idVeterinaire` INT NOT NULL,
  PRIMARY KEY (`id`, `idDossier`, `idAnimal`, `idVeterinaire`),
  INDEX `fk_Visite_2_idx` (`idDossier` ASC) VISIBLE,
  INDEX `fk_Visite_1_idx` (`idAnimal` ASC) VISIBLE,
  INDEX `fk_Veterinaire_idx` (`idVeterinaire` ASC) VISIBLE,
  CONSTRAINT `fk_Veterinaire`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Veterinaire`.`Veterinaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Veterinaire`.`Animal` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_2`
    FOREIGN KEY (`idDossier`)
    REFERENCES `Veterinaire`.`Dossier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Medicament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Medicament` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Medicament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `dosage` VARCHAR(45) NULL,
  `indications` TEXT(100) NULL,
  `effetsSecondaires` TEXT(100) NULL,
  `laboratoire` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Prescrire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Prescrire` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Prescrire` (
  `idVisite` INT NOT NULL,
  `idMedicament` INT NULL,
  `posologie` VARCHAR(45) NULL,
  INDEX `fk_Prescrire_2_idx` (`idMedicament` ASC) VISIBLE,
  INDEX `fk_Prescrire_1_idx` (`idVisite` ASC) VISIBLE,
  PRIMARY KEY (`idVisite`),
  CONSTRAINT `fk_Prescrire_1`
    FOREIGN KEY (`idVisite`)
    REFERENCES `Veterinaire`.`Visite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescrire_2`
    FOREIGN KEY (`idMedicament`)
    REFERENCES `Veterinaire`.`Medicament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Horaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Horaire` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Horaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jour` DATE NULL,
  `heureDebut` TIME NULL,
  `heureFin` TIME NULL,
  `idVeterinaire` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Horaire_Veterinaire_idx` (`idVeterinaire` ASC) VISIBLE,
  CONSTRAINT `fk_Horaire_Veterinaire`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Veterinaire`.`Veterinaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Effectuer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Effectuer` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Effectuer` (
  `idVeterinaire` INT NOT NULL,
  `idGarde` INT NULL,
  PRIMARY KEY (`idVeterinaire`),
  INDEX `GARDE` (`idGarde` ASC) VISIBLE,
  CONSTRAINT `fk_Effectuer_Veterinaire`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Veterinaire`.`Veterinaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Veterinaire`.`Garde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinaire`.`Garde` ;

CREATE TABLE IF NOT EXISTS `Veterinaire`.`Garde` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `heure_debut` TIME NULL,
  `heure_fin` TIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Effectuer`
    FOREIGN KEY (`id`)
    REFERENCES `Veterinaire`.`Effectuer` (`idGarde`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
